### ISSUE TITLE
how well does this work?

### ISSUE THREAD

**Issue by nbecker** [fstop22/nyquist_filters#1]
The only constraints imposed are in the stopband and passband, and then the 3db pt.  There is no constraint that there is nyquist symmetry about the 3dB pt.  I wonder if this works well, particularly if the rolloff is large.

**Comment by fstop22** [comment]
It works quite well.  The initial filter has nyquist symmetry around the 6 dB point.  This technique is described in detail in Fred Harris' book "Multirate Signal Processing."  The one thing that he also does is apply a 6-db/octave taper to the stopband.  According to his results, this technique produces a nyquist filter that is more efficient than standard raised/root-raised cosine pulse with regards to transition band width, number of taps, and stopband attentuation.  I still need to implement the 6-dB/octave taper.

**Comment by fstop22** [comment]
I just pushed a file showing performance of this method compared to traditional raised/root-raised cosine filters.  Used filters.py from https://github.com/veeresht/CommPy.git for comparison.
